{
 "title": "SDP_EXPORTER",
 "tags": [
  "Prometheus",
  "node_exporter",
  "sdp-exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbenv", "label": "环境选择", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "label_values(sdp_scrape_collector_success{collector=\"disk\"},node)"
   },
   { "name": "namespace", "label": "命名空间" },
   {
    "name": "pod",
    "label": "Pod名称",
    "query": "5f2110f6d180820010e38788-product-green-1-799559965d-zk9rl"
   }
  ]
 },
 "panels": [
  { "title": "磁盘使用信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SDP_EXPORTER监控配置",
   "type": "table-old",
   "description": "SDP_EXPORTER 自定义监控配置",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sdp_scrape_collector_success{collector=\"disk\"}"
    },
    { "expr": "sdp_disk_capacity_size{} - 0" },
    {
     "expr": "max(sdp_disk_used_size{}/sdp_disk_capacity_size{}*100)by(node) -0"
    }
   ]
  },
  {
   "title": "容器空间容量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sdp_container_container_size{pod=~\"$pod\"} )"
    }
   ]
  },
  {
   "title": "Pod占用磁盘空间",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(sdp_container_container_log_std_size{node=~\"$hostname\"} +  sdp_container_container_log_tomcat_size{node=~\"$hostname\"} + sdp_container_container_size{node=~\"$hostname\"}) by(node,pod)  > 256*1024*1024"
    }
   ]
  },
  {
   "title": "容器标准日志",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sdp_container_container_log_std_size{pod=~\"$pod\"} )"
    }
   ]
  },
  {
   "title": "容器Tomcat日志",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sdp_container_container_log_tomcat_size{pod=~\"$pod\"} )"
    }
   ]
  }
 ]
}